server {
    listen 80;
    listen  [::]:80;
    server_name  localhost;

    root /usr/share/nginx/html/crew-trip/fe/browser;
    index index.html;

    # Serve the Frontend application (Angular)
    location / {
        try_files $uri /index.html;
    }

    # Optional: Enable gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Optional: Add caching headers for static files
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
