# HTTP Server (Redirect to HTTPS)
server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

# HTTPS Server (Serving Angular App)
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name localhost;

    # SSL Configuration
    ssl_certificate /etc/nginx/ssl/crewtrip_certificate.pem;
    ssl_certificate_key /etc/nginx/ssl/private.key;
#     ssl_trusted_certificate /etc/nginx/ssl/ca_bundle.crt;

    # Optional: Strong Security Settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Serve Angular App
    root /usr/share/nginx/html/crew-trip/fe/browser;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Enable gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Cache static files
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
