import { ex } from 'node_modules/@fullcalendar/core/internal-common';
import { PlanCategoryEnum } from '../../../budget-procurement.model';

export const formula: any = {

  //Số chuyến bay theo tàu (công thức của kế hoạch mua sắm)
  totalFlightByAircraft: {
    formula: 'data.planFlightPeriod * data.flightOvernightRate'
  },

  //Tổng tiền xe chở tổ bay (ngoại tệ)
  totalAmountForeignTransport: {
    formula: 'data.totalFlightMonth * 2 * data.priceCrewTransport',
    groupFormula: 'aircraftType && period',
  },
  //Số phòng đơn
  singleRoom: {
    formula: 'data.overnight * data.totalFlightByAircraft * data.pilotNumber + (data.attendantNumber % 2 === 0 ? 0 : data.totalFlightByAircraft)',
  },
  //Số phòng đôi
  doubleRoom: {
    formula: 'data.overnight * data.totalFlightByAircraft * (data.attendantNumber % 2 === 0 ? (data.attendantNumber/2) : ((data.attendantNumber - 1)/2)) ',
  },
  //Số phòng đơn dự phòng do lẻ nam nữ
  singleRoomReserved: {
    formula: 'data.singleRoom * generalData.rateForSingle'
  },
  //Số phòng đơn early-checkin dự kiến
  singleRoomEarly: {
    formula: '1 * data.totalFlightEarlyCheckin * data.pilotNumber + (data.attendantNumber % 2 === 0 ? 0 : data.totalFlightByAircraft)'
  },
  //Số phòng đôi early-checkin dự kiến
  doubleRoomEarly: {
    formula: '1 * data.totalFlightEarlyCheckin * (data.attendantNumber % 2 === 0 ? (data.attendantNumber/2) : ((data.attendantNumber - 1)/2))'
  },
  //Số phòng đơn early-checkin dự kiến do lẻ nam nữ
  singleRoomEarlyReserved: {
    formula: 'data.singleRoomEarly * generalData.rateForSingle'
  },
  //Số phòng đơn late checkout dự kiến
  singleRoomLate: {
    formula: '1 * data.totalFlightLateCheckout * data.pilotNumber + (data.attendantNumber % 2 === 0 ? 0 : data.totalFlightByAircraft)'
  },
  //Số phòng đôi late checkout dự kiến
  doubleRoomLate: {
    formula: '1 * data.totalFlightLateCheckout * (data.attendantNumber % 2 === 0 ? (data.attendantNumber/2) : ((data.attendantNumber - 1)/2))'
  },
  //Số phòng đơn late checkout dự kiến do lẻ nam nữ
  singleRoomLateReserved: {
    formula: 'data.singleRoomLate * generalData.rateForSingle'
  },
  //Thành tiền ngoại tệ, - phòng đơn 
  totalAmountForeignSingleRoom: {
    formula: 'data.singleRoom * data.priceSingleRoom'
  },
  //Thành tiền ngoại tệ,  - phòng đôi
  totalAmountForeignDoubleRoom: {
    formula: 'data.doubleRoom * data.priceDoubleRoom'
  },
  //Thành tiền ngoại tệ,  - phòng early-checkin 
  totalAmountForeignEarly: {
    formula: '(data.singleRoomEarly + data.singleRoomEarlyReserved) * data.priceSingleRoomEarly + data.doubleRoomEarly * data.priceDoubleRoomEarly'
  },
  //Thành tiền ngoại tệ, - phòng late checkout
  totalAmountForeignLate: {
    formula: '(data.singleRoomLate + data.singleRoomLateReserved) * data.priceSingleRoomLate + data.doubleRoomLate * data.priceDoubleRoomLate'
  },
  //Tổng tiền theo loại máy bay
  totalAmountAircraft: {
    formula: 'data.totalAmountForeignSingleRoom + data.totalAmountForeignDoubleRoom + data.totalAmountForeignEarly + data.totalAmountForeignLate + data.totalAmountForeignTransport'
  },
  // Tổng tiền ngoại tệ - Chưa bao gồm VAT
  totalAmountForeign: {
    formula: '(data.singleRoom + data.singleRoomReserved + data.singleRoomOther) * data.priceSingleRoom '
      + ' + (data.doubleRoom + data.doubleRoomOther ) * data.priceDoubleRoom '
      + ' + (data.singleRoomEarly + data.singleRoomEarlyReserved) * data.priceSingleRoomEarly '
      + ' + (data.doubleRoomEarly * data.priceDoubleRoomEarly) '
      + ' + (data.singleRoomLate + data.singleRoomLateReserved) * data.priceSingleRoomLate '
      + ' + (data.doubleRoomLate * data.priceDoubleRoomLate) '
      + ' + (data.totalFlightMonth * 2 * data.priceCrewTransport) ',
    formulaUpdateBudgetPlan: ' data.singleRoom * data.priceSingleRoom '
      + ' + data.doubleRoom * data.priceDoubleRoom '
      + ' + data.singleRoomEarly * data.priceSingleRoomEarly '
      + ' + data.doubleRoomEarly * data.priceDoubleRoomEarly '
      + ' + data.singleRoomLate * data.priceSingleRoomLate '
      + ' + data.doubleRoomLate * data.priceDoubleRoomLate '
      + ' + (data.totalFlightMonth * 2 * data.priceCrewTransport) ',
    groupFormula: 'period',
  },
  //Tổng tiền ngoại tệ - Bao gồm VAT
  totalAmountForeignVat: {
    formula: '(data.totalAmountForeignSingleRoom + data.totalAmountForeignDoubleRoom + data.totalAmountForeignEarly + data.totalAmountForeignLate + data.totalAmountForeignTransport)',
    groupFormula: 'period',
  },
  //Tổng tiền VND - bao gồm VAT
  totalAmountVat: {
    formula: 'data.totalAmountForeignVat * data.rateInPeriod',
    groupFormula: 'period',
  },
  //Tổng tiền VND - chưa bao gồm VAT
  totalAmount: {
    formula: 'data.totalAmountForeign * data.rateInPeriod',
    groupFormula: 'period',
  },
  //Tổng số phòng đơn
  totalSingleRoom: {
    formula: 'data.singleRoom + data.singleRoomReserved + data.singleRoomOther',
  },
  //Tổng số phòng đôi
  totalDoubleRoom: {
    formula: 'data.doubleRoom + data.doubleRoomOther',
  },

}

export function getHeaderRowDef1(contractData: any, type: string): string[] {
  const columns: { column: string, visible: boolean }[] = [
    { column: "month", visible: true },
    { column: "aircraftType", visible: true },
    { column: "overnight", visible: true },
    { column: "numberOfRooms", visible: true },
    { column: "numberOfRoomsForOthers", visible: true },
    { column: "numberOfEstimatedEarlyCheckInRooms", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "numberOfEstimatedLateCheckoutRooms", visible: !!contractData.lateCheckoutFeeFlag },
    //start phần kế hoạch mua sắm
    { column: "unitPriceIncludingVat", visible: type === PlanCategoryEnum.PROCUREMENT }, // (Đơn giá bao gồm vat) 
    { column: "priceCrewTransport", visible: type === PlanCategoryEnum.PROCUREMENT && !!contractData.priceCrewTransportFlag }, // (Đơn giá xe chở tổ bay/lượt) 
    // end phần kế hoạch mua sắm
    { column: "totalAmountForeignTransport", visible: !!contractData.crewTransportFeeFlag },
    { column: "totalAmountForeignColspan", visible: true },
    { column: "totalAmountColspan", visible: true }
  ]
  return columns.filter((column: any) => column.visible).map((column: any) => column.column)
}

export function getHeaderRowDef2(contractData: any, type: string): string[] {
  const columns: { column: string, visible: boolean }[] = [
    { column: "singleRoom", visible: true },
    { column: "doubleRoom", visible: true },
    { column: "singleRoomReserved", visible: true },
    { column: "singleRoomOther", visible: true },
    { column: "doubleRoomOther", visible: true },
    { column: "singleRoomEarly", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "doubleRoomEarly", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "singleRoomEarlyReserved", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "singleRoomLate", visible: !!contractData.lateCheckoutFeeFlag },
    { column: "doubleRoomLate", visible: !!contractData.lateCheckoutFeeFlag },
    { column: "singleRoomLateReserved", visible: !!contractData.lateCheckoutFeeFlag },
    //start phần kế hoạch mua sắm
    { column: "priceSingleRoom", visible: type === PlanCategoryEnum.PROCUREMENT }, // (Đơn giá phòng đơn) 
    { column: "priceDoubleRoom", visible: type === PlanCategoryEnum.PROCUREMENT }, // (Đơn giá phòng đôi) 
    { column: "priceSingleRoomEarly", visible: type === PlanCategoryEnum.PROCUREMENT && !!contractData.earlyCheckinFeeFlag }, // (Đơn giá Early-checkin phòng đơn) 
    { column: "priceDoubleRoomEarly", visible: type === PlanCategoryEnum.PROCUREMENT && !!contractData.earlyCheckinFeeFlag }, // (Đơn giá Early-checkin phòng đôi) 
    { column: "priceSingleRoomLate", visible: type === PlanCategoryEnum.PROCUREMENT && !!contractData.lateCheckoutFeeFlag }, // (Đơn giá late checkout phòng đơn) 
    { column: "priceDoubleRoomLate", visible: type === PlanCategoryEnum.PROCUREMENT && !!contractData.lateCheckoutFeeFlag }, // (Đơn giá late check out phòng đôi) 
    // end phần kế hoạch mua sắm
    { column: "totalAmountForeign", visible: true },
    { column: "totalAmountForeignVat", visible: true },
    { column: "totalAmount", visible: true },
    { column: "totalAmountVat", visible: true },
  ];
  return columns.filter((column: any) => column.visible).map((column: any) => column.column)
}

export function getRowDef(contractData: any, type: string): string[] {
  const columns = [
    { column: "month", visible: true },
    { column: "aircraftType", visible: true },
    { column: "overnight", visible: true },
    { column: "singleRoom", visible: true },
    { column: "doubleRoom", visible: true },
    { column: "singleRoomReserved", visible: true },
    { column: "singleRoomOther", visible: true },
    { column: "doubleRoomOther", visible: true },
    { column: "singleRoomEarly", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "doubleRoomEarly", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "singleRoomEarlyReserved", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "singleRoomLate", visible: !!contractData.lateCheckoutFeeFlag },
    { column: "doubleRoomLate", visible: !!contractData.lateCheckoutFeeFlag },
    { column: "singleRoomLateReserved", visible: !!contractData.lateCheckoutFeeFlag },
    //start phần kế hoạch mua sắm
    { column: "priceSingleRoom", visible: type === PlanCategoryEnum.PROCUREMENT },
    { column: "priceDoubleRoom", visible: type === PlanCategoryEnum.PROCUREMENT },
    { column: "priceSingleRoomEarly", visible: type === PlanCategoryEnum.PROCUREMENT && !!contractData.earlyCheckinFeeFlag },
    { column: "priceDoubleRoomEarly", visible: type === PlanCategoryEnum.PROCUREMENT && !!contractData.earlyCheckinFeeFlag },
    { column: "priceSingleRoomLate", visible: type === PlanCategoryEnum.PROCUREMENT && !!contractData.lateCheckoutFeeFlag },
    { column: "priceDoubleRoomLate", visible: type === PlanCategoryEnum.PROCUREMENT && !!contractData.lateCheckoutFeeFlag },
    { column: "priceCrewTransport", visible: type === PlanCategoryEnum.PROCUREMENT && !!contractData.priceCrewTransportFlag },
    // end phần kế hoạch mua sắm
    { column: "totalAmountForeignTransport", visible: !!contractData.crewTransportFeeFlag },
    { column: "totalAmountForeign", visible: true },
    { column: "totalAmountForeignVat", visible: true },
    { column: "totalAmount", visible: true },
    { column: "totalAmountVat", visible: true },
  ];
  return columns.filter((column: any) => column.visible).map((column: any) => column.column)
}

const FlagTypeEnum = {
  EARLY_CHECKIN: 'earlyCheckinFeeFlag',
  LATE_CHECKOUT: 'lateCheckoutFeeFlag',
  CREW_TRANSPORT: 'priceCrewTransportFlag'
}

function checkVisibleColumn(contractData: any, flagType: string, type: string): boolean {
  // earlyCheckinContractFlag: new FormControl(false),
  // lateCheckoutContractFlag: new FormControl(false),
  //   (1) trường hợp có hợp đồng, trong hợp đồng có HHDV = phí ECI, LCO 
  // => có tích 2 checkbox -> bảng KHNS, KHMS hiển thị các cột liên quan đến ECI, LCO
  // => Khi người dùng bỏ tích chọn -> bảng KHNS vẫn hiển thị các cột ECI, LCO. Bảng KHMS k hiển thị các cột ECI, LCO

  if (contractData.haveContract) {
    if (contractData.earlyCheckinContractFlag && flagType === FlagTypeEnum.EARLY_CHECKIN && !!contractData.earlyCheckinFeeFlag) {
      return true
    } else if (contractData.earlyCheckinContractFlag && flagType === FlagTypeEnum.EARLY_CHECKIN && !contractData.earlyCheckinFeeFlag && type === PlanCategoryEnum.BUDGET) {
      return true
    } else if (contractData.lateCheckoutContractFlag && flagType === FlagTypeEnum.LATE_CHECKOUT && !!contractData.lateCheckoutFeeFlag) {
      return true;
    } else if (contractData.lateCheckoutContractFlag && flagType === FlagTypeEnum.LATE_CHECKOUT && !contractData.lateCheckoutFeeFlag && type === PlanCategoryEnum.BUDGET) {
      return true
    }
    //   (2) trường hợp có hợp đồng, trong hợp đồng KHÔNG có HHDV = phí ECI, LCO 
    // => không tích 2 checkbox -> bảng KHNS, KHMS KHÔNG hiển thị các cột liên quan đến ECI, LCO
    // => Khi người dùng CÓ tích chọn -> bảng KHNS KHÔNG hiển thị các cột ECI, LCO. Bảng KHMS CÓ hiển thị các cột ECI, LCO
    else if (!contractData.earlyCheckinContractFlag && flagType === FlagTypeEnum.EARLY_CHECKIN && !!contractData.earlyCheckinFeeFlag && type === PlanCategoryEnum.PROCUREMENT) {
      return true;
    } else if (!contractData.lateCheckoutContractFlag && flagType === FlagTypeEnum.LATE_CHECKOUT && !!contractData.lateCheckoutFeeFlag && type === PlanCategoryEnum.PROCUREMENT) {
      return true;
    }

  }
  //   (3) Trường hợp không có hợp đồng -> vào kịch bay mùa (NETLINE_FLIGHT_LEGS_MASTER) theo điều kiện: năm làm kế hoạch = năm của trường min_dep_at:
  // + Check ECI: mã thị trường = ARR_AP_SCHED   -> nếu có 1 dòng có cột ECI  = 1 -> có tích chọn checkbox ECI 
  // -> cả 2 bảng KHNS, KHMS đều hiện các cột liên quan đến ECI. Khi người dùng bỏ tích chọn -> cả 2 bảng KHNS, KHMS đều không hiện các cột liên quan đến ECI
  // + Check LCO: mã thị trường = DEP_AP_SCHED  -> nếu có 1 gdòng có cột LCO = 1 -> có tích chọn checkbox LCO
  // -> cả 2 bảng KHNS, KHMS đều hiện các cột liên quan đến LCO. Khi người dùng bỏ tích chọn -> cả 2 bảng KHNS, KHMS đều không hiện các cột liên quan đến LCO
  // + nếu tất cả các dòng đều có ECI = 0, LCO = 0 -> KHÔNG tích chọn 2 checkbox
  // -> 2 bảng KHNS, KHMS KHÔNG hiện các cột ECI, LCO. Khi người dùng tích chọn check box ECI thì cả 2 bảng KHNS, KHMS đều hiện các cột liên quan đến ECI (LCO cũng tương tự)
  return false
}


export const exampleData =
  [
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-11-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 0,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-11-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 0,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-11-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-11-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    }
    ,
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-12-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-12-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-12-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-12-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-01-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-01-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-01-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-01-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-02-28T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-02-28T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-02-28T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-02-28T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-03-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-03-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-03-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-03-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-04-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-04-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-04-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-04-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-05-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-05-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-05-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-05-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-06-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-06-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-06-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-06-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-07-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-07-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-07-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-07-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-08-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-08-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-08-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-08-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-09-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-09-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-09-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-09-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-10-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-10-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-10-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-10-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-11-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-11-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-11-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-11-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    }
  ];


export const planFlightByOvernight = [
  {
    numberOfOvernight: 1,
    flightRate: 20
  },
  {
    numberOfOvernight: 2,
    flightRate: 30
  },
  {
    numberOfOvernight: 3,
    flightRate: 40
  }
]

export function checkChange(value1: any, value2: any) {
  return value1 !== value2;
}
