import { PlanCategoryEnum } from "../../../../budget-procurement/budget-procurement.model";

export const formula: any = {

    //Số chuyến bay theo tàu (công thức của kế hoạch mua sắm)
    totalFlightByAircraft: {
        formula: 'ctz(data.planFlightPeriod) * ctz(data.flightOvernightRate)'
    },

    //Tổng tiền xe chở tổ bay (ngoại tệ)
    totalAmountForeignTransport: {
        formula: 'ctz(data.totalFlightMonth) * 2 * ctz(data.priceCrewTransport)',
        groupFormula: 'aircraftType && period',
    },
    //Số phòng đơn
    singleRoom: {
        formula: 'ctz(data.overnight) * ctz(data.totalFlightByAircraft) * ctz(data.pilotNumber) + (ctz(data.attendantNumber) % 2 === 0 ? 0 : ctz(data.totalFlightByAircraft))',
    },
    //Số phòng đôi
    doubleRoom: {
        formula: 'ctz(data.overnight) * ctz(data.totalFlightByAircraft) * (ctz(data.attendantNumber) % 2 === 0 ? (ctz(data.attendantNumber)/2) : ((ctz(data.attendantNumber) - 1)/2)) ',
    },
    //Số phòng đơn dự phòng do lẻ nam nữ
    singleRoomReserved: {
        formula: 'ctz(data.singleRoom) * ctz(generalData.rateForSingle)'
    },
    //Số phòng đơn early-checkin dự kiến
    singleRoomEarly: {
        formula: '1 * ctz(data.totalFlightEarlyCheckin) * ctz(data.pilotNumber) + (ctz(data.attendantNumber) % 2 === 0 ? 0 : ctz(data.totalFlightByAircraft))'
    },
    //Số phòng đôi early-checkin dự kiến
    doubleRoomEarly: {
        formula: '1 * ctz(data.totalFlightEarlyCheckin) * (ctz(data.attendantNumber) % 2 === 0 ? (ctz(data.attendantNumber)/2) : ((ctz(data.attendantNumber) - 1)/2))'
    },
    //Số phòng đơn early-checkin dự kiến do lẻ nam nữ
    singleRoomEarlyReserved: {
        formula: 'ctz(data.singleRoomEarly) * ctz(generalData.rateForSingle)'
    },
    //Số phòng đơn late checkout dự kiến
    singleRoomLate: {
        formula: '1 * ctz(data.totalFlightLateCheckout) * ctz(data.pilotNumber) + (ctz(data.attendantNumber) % 2 === 0 ? 0 : ctz(data.totalFlightByAircraft))'
    },
    //Số phòng đôi late checkout dự kiến
    doubleRoomLate: {
        formula: '1 * ctz(data.totalFlightLateCheckout) * (ctz(data.attendantNumber) % 2 === 0 ? (ctz(data.attendantNumber)/2) : ((ctz(data.attendantNumber) - 1)/2))'
    },
    //Số phòng đơn late checkout dự kiến do lẻ nam nữ
    singleRoomLateReserved: {
        formula: 'ctz(data.singleRoomLate) * ctz(generalData.rateForSingle)'
    },
    //Thành tiền ngoại tệ, - phòng đơn 
    totalAmountForeignSingleRoom: {
        formula: 'ctz(data.singleRoom) * ctz(data.priceSingleRoom)'
    },
    //Thành tiền ngoại tệ,  - phòng đôi
    totalAmountForeignDoubleRoom: {
        formula: 'ctz(data.doubleRoom) * ctz(data.priceDoubleRoom)'
    },
    //Thành tiền ngoại tệ,  - phòng early-checkin 
    totalAmountForeignEarly: {
        formula: '(ctz(data.singleRoomEarly) + ctz(data.singleRoomEarlyReserved)) * ctz(data.priceSingleRoomEarly) + ctz(data.doubleRoomEarly) * ctz(data.priceDoubleRoomEarly)'
    },
    //Thành tiền ngoại tệ, - phòng late checkout
    totalAmountForeignLate: {
        formula: '(ctz(data.singleRoomLate) + ctz(data.singleRoomLateReserved)) * ctz(data.priceSingleRoomLate) + ctz(data.doubleRoomLate) * ctz(data.priceDoubleRoomLate)'
    },
    //Tổng tiền theo loại máy bay
    totalAmountAircraft: {
        formula: 'ctz(data.totalAmountForeignSingleRoom) + ctz(data.totalAmountForeignDoubleRoom) + ctz(data.totalAmountForeignEarly) + ctz(data.totalAmountForeignLate) + ctz(data.totalAmountForeignTransport)'
    },
    // Tổng tiền ngoại tệ - Chưa bao gồm VAT
    totalAmountForeign: {
        formula: '(ctz(data.singleRoom) + ctz(data.singleRoomReserved) + ctz(data.singleRoomOther)) * ctz(data.priceSingleRoom) '
            + ' + (ctz(data.doubleRoom) + ctz(data.doubleRoomOther) ) * ctz(data.priceDoubleRoom) '
            + ' + (ctz(data.singleRoomEarly) + ctz(data.singleRoomEarlyReserved)) * ctz(data.priceSingleRoomEarly) '
            + ' + (ctz(data.doubleRoomEarly) * ctz(data.priceDoubleRoomEarly)) '
            + ' + (ctz(data.singleRoomLate) + ctz(data.singleRoomLateReserved)) * ctz(data.priceSingleRoomLate) '
            + ' + (ctz(data.doubleRoomLate) * ctz(data.priceDoubleRoomLate)) '
            + ' + (ctz(data.totalFlightMonth )* 2 * ctz(data.priceCrewTransport)) ',
        formulaUpdateBudgetPlan: ' ctz(data.singleRoom) * ctz(data.priceSingleRoom) '
            + ' + ctz(data.doubleRoom) * ctz(data.priceDoubleRoom) '
            + ' + ctz(data.singleRoomEarly) * ctz(data.priceSingleRoomEarly) '
            + ' + ctz(data.doubleRoomEarly) * ctz(data.priceDoubleRoomEarly) '
            + ' + ctz(data.singleRoomLate) * ctz(data.priceSingleRoomLate) '
            + ' + ctz(data.doubleRoomLate) * ctz(data.priceDoubleRoomLate) '
            + ' + (ctz(data.totalFlightMonth) * 2 * ctz(data.priceCrewTransport)) ',
        groupFormula: 'period',
    },
    //Tổng tiền ngoại tệ - Bao gồm VAT
    totalAmountForeignVat: {
        formula: '(ctz(data.totalAmountForeignSingleRoom) + ctz(data.totalAmountForeignDoubleRoom) + ctz(data.totalAmountForeignEarly) + ctz(data.totalAmountForeignLate) + ctz(data.totalAmountForeignTransport))',
        groupFormula: 'period',
    },
    //Tổng tiền VND - bao gồm VAT
    totalAmountVat: {
        formula: 'ctz(data.totalAmountForeignVat) * ctz(data.rateInPeriod)',
        groupFormula: 'period',
    },
    //Tổng tiền VND - chưa bao gồm VAT
    totalAmount: {
        formula: 'ctz(data.totalAmountForeign) * ctz(data.rateInPeriod)',
        groupFormula: 'period',
    },
    //Tổng số phòng đơn
    totalSingleRoom: {
        formula: 'ctz(data.singleRoom) + ctz(data.singleRoomReserved) + ctz(data.singleRoomOther)',
        groupFormula: 'period'
    },
    //Tổng số phòng đôi
    totalDoubleRoom: {
        formula: 'ctz(data.doubleRoom) + ctz(data.doubleRoomOther)',
        groupFormula: 'period'
    },

}

export function getHeaderRowDef1(contractData: any): string[] {
    const columns: { column: string, visible: boolean }[] = [
        { column: "month", visible: true },
        { column: "aircraftType", visible: true },
        { column: "overnight", visible: true },
        { column: "numberFlight", visible: true },
        { column: "numberOfRooms", visible: true },
        { column: "numberOfRoomsForOthers", visible: true },
        { column: "numberOfEstimatedEarlyCheckInRooms", visible: checkVisibleColumn(contractData, FlagTypeEnum.EARLY_CHECKIN) },
        { column: "numberOfEstimatedLateCheckoutRooms", visible: checkVisibleColumn(contractData, FlagTypeEnum.LATE_CHECKOUT) },
        { column: 'totalRoom', visible: true },
        { column: "totalAmountForeignTransport", visible: !!contractData.crewTransportFeeFlag },
        { column: "totalAmountForeignColspan", visible: true },
        { column: "totalAmountColspan", visible: true }
    ]
    return columns.filter((column: any) => column.visible).map((column: any) => column.column)
}

export function getHeaderRowDef2(contractData: any): string[] {
    const columns: { column: string, visible: boolean }[] = [
        { column: "singleRoom", visible: true },
        { column: "doubleRoom", visible: true },
        { column: "singleRoomReserved", visible: true },
        { column: "singleRoomOther", visible: true },
        { column: "doubleRoomOther", visible: true },
        { column: "singleRoomEarly", visible: checkVisibleColumn(contractData, FlagTypeEnum.EARLY_CHECKIN) },
        { column: "doubleRoomEarly", visible: checkVisibleColumn(contractData, FlagTypeEnum.EARLY_CHECKIN) },
        { column: "singleRoomEarlyReserved", visible: checkVisibleColumn(contractData, FlagTypeEnum.EARLY_CHECKIN) },
        { column: "singleRoomLate", visible: checkVisibleColumn(contractData, FlagTypeEnum.LATE_CHECKOUT) },
        { column: "doubleRoomLate", visible: checkVisibleColumn(contractData, FlagTypeEnum.LATE_CHECKOUT) },
        { column: "singleRoomLateReserved", visible: checkVisibleColumn(contractData, FlagTypeEnum.LATE_CHECKOUT) },
        { column: 'totalSingleRoom', visible: true },
        { column: 'totalDoubleRoom', visible: true },
        { column: "totalAmountForeign", visible: true },
        { column: "totalAmountForeignVat", visible: true },
        { column: "totalAmount", visible: true },
        { column: "totalAmountVat", visible: true },
    ];
    return columns.filter((column: any) => column.visible).map((column: any) => column.column)
}

export function getRowDef(contractData: any): string[] {
    const columns = [
        { column: "month", visible: true },
        { column: "aircraftType", visible: true },
        { column: "overnight", visible: true },
        { column: "numberFlight", visible: true },
        { column: "singleRoom", visible: true },
        { column: "doubleRoom", visible: true },
        { column: "singleRoomReserved", visible: true },
        { column: "singleRoomOther", visible: true },
        { column: "doubleRoomOther", visible: true },
        { column: "singleRoomEarly", visible: checkVisibleColumn(contractData, FlagTypeEnum.EARLY_CHECKIN) },
        { column: "doubleRoomEarly", visible: checkVisibleColumn(contractData, FlagTypeEnum.EARLY_CHECKIN) },
        { column: "singleRoomEarlyReserved", visible: checkVisibleColumn(contractData, FlagTypeEnum.EARLY_CHECKIN) },
        { column: "singleRoomLate", visible: checkVisibleColumn(contractData, FlagTypeEnum.LATE_CHECKOUT) },
        { column: "doubleRoomLate", visible: checkVisibleColumn(contractData, FlagTypeEnum.LATE_CHECKOUT) },
        { column: "singleRoomLateReserved", visible: checkVisibleColumn(contractData, FlagTypeEnum.LATE_CHECKOUT) },
        { column: 'totalSingleRoom', visible: true },
        { column: 'totalDoubleRoom', visible: true },
        { column: "totalAmountForeignTransport", visible: !!contractData.crewTransportFeeFlag },
        { column: "totalAmountForeign", visible: true },
        { column: "totalAmountForeignVat", visible: true },
        { column: "totalAmount", visible: true },
        { column: "totalAmountVat", visible: true },
    ];
    return columns.filter((column: any) => column.visible).map((column: any) => column.column)
}

const FlagTypeEnum = {
    EARLY_CHECKIN: 'earlyCheckinFeeFlag',
    LATE_CHECKOUT: 'lateCheckoutFeeFlag',
    CREW_TRANSPORT: 'priceCrewTransportFlag'
}

function checkVisibleColumn(contractData: any, flagType: string): boolean {
    if (contractData.haveContract) {
        if (contractData.earlyCheckinContractFlag && flagType === FlagTypeEnum.EARLY_CHECKIN) {
            return true
        } else if (contractData.lateCheckoutContractFlag && flagType === FlagTypeEnum.LATE_CHECKOUT) {
            return true;
        }

    } else {
        if (flagType === FlagTypeEnum.EARLY_CHECKIN) {
            return true;
        } else if (flagType === FlagTypeEnum.LATE_CHECKOUT) {
            return true
        }

    }
    return false
}


export const exampleData =
    [
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2024-11-30T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 0,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2024-11-30T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 0,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2024-11-30T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2024-11-30T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        }
        ,
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2024-12-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2024-12-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2024-12-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2024-12-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-01-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-01-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-01-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-01-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-02-28T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-02-28T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-02-28T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-02-28T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-03-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-03-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-03-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-03-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-04-30T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-04-30T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-04-30T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-04-30T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-05-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-05-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-05-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-05-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-06-30T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-06-30T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-06-30T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-06-30T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-07-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-07-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-07-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-07-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-08-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-08-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-08-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-08-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-09-30T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-09-30T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-09-30T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-09-30T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-10-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-10-31T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-10-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-10-31T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-11-30T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-11-30T17:00:00.000Z",
            "aircraftType": "B787",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-11-30T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 1,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        },
        {
            "id": 1,
            "planBudgetProcSummaryId": 101,
            "type": "Hotel",
            "periodStart": "2025-11-30T17:00:00.000Z",
            "aircraftType": "A321",
            "periodEnd": "2024-12-31",
            "overnight": 2,
            "singleRoom": 10,
            "doubleRoom": 5,
            "singleRoomReserved": 2,
            "singleRoomOther": 1,
            "doubleRoomOther": 1,
            "singleRoomEarly": 1,
            "doubleRoomEarly": 1,
            "singleRoomEarlyReserved": 1,
            "singleRoomLate": 1,
            "doubleRoomLate": 1,
            "singleRoomLateReserved": 1,
            "totalAmountForeignTransport": 1000,
            "totalAmountForeign": 5000,
            "totalAmount": 6000,
            "totalAmountVat": 6600,
            "priceSingleRoom": 100,
            "priceDoubleRoom": 200,
            "priceSingleRoomEarly": 150,
            "priceDoubleRoomEarly": 250,
            "priceSingleRoomLate": 120,
            "priceDoubleRoomLate": 220,
            "priceCrewTransport": 75000,
            "totalFlightMonth": 100,
            "carRate": 75000,
            "totalAmountForeignSingleRoom": 100,
            "totalAmountForeignDoubleRoom": 50,
            "totalAmountForeignEarly": 50,
            "totalAmountForeignLate": 50,
            "totalAmountAircraft": 1000,
            "rateForeign": 1.1,
            "vat": 10,
            "totalFlightByAircraft": 50,
            "numberOfPilots": 4,
            "attendantNumber": 5,
            "rateForSingle": 1.1,
            "numberOfEarlyFlights": 10,
            "numberOfLateFlights": 5,
            "overnightLate": 1
        }
    ];


export const planFlightByOvernight = [
    {
        numberOfOvernight: 1,
        flightRate: 20
    },
    {
        numberOfOvernight: 2,
        flightRate: 30
    },
    {
        numberOfOvernight: 3,
        flightRate: 40
    }
]

export function checkChange(value1: any, value2: any) {
    return value1 !== value2;
}
