import { ex } from "node_modules/@fullcalendar/core/internal-common"

export const formula: any = {

  //Số chuyến bay theo tàu (công thức của kế hoạch mua sắm)
  totalFlightByAircraft: {
    formula: 'data.planFlightPeriod * data.flightOvernightRate'
  },

  //Tổng tiền xe chở tổ bay (ngoại tệ)
  totalAmountForeignTransport: {
    formula: 'data.totalFlightMonth * 2 * data.priceCrewTransport',
    groupFormula: 'aircraftType && period',
  },
  //Số phòng đơn
  singleRoom: {
    formula: 'data.overnight * data.totalFlightByAircraft * data.pilotNumber + (data.attendantNumber % 2 === 0 ? 0 : data.totalFlightByAircraft)',
  },
  //Số phòng đôi
  doubleRoom: {
    formula: 'data.overnight * data.totalFlightByAircraft * (data.attendantNumber % 2 === 0 ? (data.attendantNumber/2) : ((data.attendantNumber - 1)/2)) ',
  },
  //Số phòng đơn dự phòng do lẻ nam nữ
  singleRoomReserved: {
    formula: 'data.singleRoom * generalData.rateForSingle'
  },
  //Số phòng đơn early-checkin dự kiến
  singleRoomEarly: {
    formula: '1 * data.totalFlightEarlyCheckin * data.pilotNumber + (data.attendantNumber % 2 === 0 ? 0 : data.totalFlightByAircraft)'
  },
  //Số phòng đôi early-checkin dự kiến
  doubleRoomEarly: {
    formula: '1 * data.totalFlightEarlyCheckin * (data.attendantNumber % 2 === 0 ? (data.attendantNumber/2) : ((data.attendantNumber - 1)/2))'
  },
  //Số phòng đơn early-checkin dự kiến do lẻ nam nữ
  singleRoomEarlyReserved: {
    formula: 'data.singleRoomEarly * generalData.rateForSingle'
  },
  //Số phòng đơn late checkout dự kiến
  singleRoomLate: {
    formula: '1 * data.totalFlightLateCheckout * data.pilotNumber + (data.attendantNumber % 2 === 0 ? 0 : data.totalFlightByAircraft)'
  },
  //Số phòng đôi late checkout dự kiến
  doubleRoomLate: {
    formula: '1 * data.totalFlightLateCheckout * (data.attendantNumber % 2 === 0 ? (data.attendantNumber/2) : ((data.attendantNumber - 1)/2))'
  },
  //Số phòng đơn late checkout dự kiến do lẻ nam nữ
  singleRoomLateReserved: {
    formula: 'data.singleRoomLate * generalData.rateForSingle'
  },
  //Thành tiền ngoại tệ, - phòng đơn 
  totalAmountForeignSingleRoom: {
    formula: 'data.singleRoom * data.priceSingleRoom'
  },
  //Thành tiền ngoại tệ,  - phòng đôi
  totalAmountForeignDoubleRoom: {
    formula: 'data.doubleRoom * data.priceDoubleRoom'
  },
  //Thành tiền ngoại tệ,  - phòng early-checkin 
  totalAmountForeignEarly: {
    formula: '(data.singleRoomEarly + data.singleRoomEarlyReserved) * data.priceSingleRoomEarly + data.doubleRoomEarly * data.priceDoubleRoomEarly'
  },
  //Thành tiền ngoại tệ, - phòng late checkout
  totalAmountForeignLate: {
    formula: '(data.singleRoomLate + data.singleRoomLateReserved) * data.priceSingleRoomLate + data.doubleRoomLate * data.priceDoubleRoomLate'
  },
  //Tổng tiền theo loại máy bay
  totalAmountAircraft: {
    formula: 'data.totalAmountForeignSingleRoom + data.totalAmountForeignDoubleRoom + data.totalAmountForeignEarly + data.totalAmountForeignLate + data.totalAmountForeignTransport'
  },
  // Tổng tiền ngoại tệ - Chưa bao gồm VAT
  totalAmountForeign: {
    formula: '(data.singleRoom + data.singleRoomReserved + data.singleRoomOther) * data.priceSingleRoom '
      + ' + (data.doubleRoom + data.doubleRoomOther ) * data.priceDoubleRoom '
      + ' + (data.singleRoomEarly + data.singleRoomEarlyReserved) * data.priceSingleRoomEarly '
      + ' + (data.doubleRoomEarly * data.priceDoubleRoomEarly) '
      + ' + (data.singleRoomLate + data.singleRoomLateReserved) * data.priceSingleRoomLate '
      + ' + (data.doubleRoomLate * data.priceDoubleRoomLate) '
      + ' + (data.totalFlightMonth * 2 * data.priceCrewTransport) ',
    formulaUpdateBudgetPlan: ' data.singleRoom * data.priceSingleRoom '
      + ' + data.doubleRoom * data.priceDoubleRoom '
      + ' + data.singleRoomEarly * data.priceSingleRoomEarly '
      + ' + data.doubleRoomEarly * data.priceDoubleRoomEarly '
      + ' + data.singleRoomLate * data.priceSingleRoomLate '
      + ' + data.doubleRoomLate * data.priceDoubleRoomLate '
      + ' + (data.totalFlightMonth * 2 * data.priceCrewTransport) ',
    groupFormula: 'period',
  },
  //Tổng tiền ngoại tệ - Bao gồm VAT
  totalAmountForeignVat: {
    formula: '(data.totalAmountForeignSingleRoom + data.totalAmountForeignDoubleRoom + data.totalAmountForeignEarly + data.totalAmountForeignLate + data.totalAmountForeignTransport)',
    groupFormula: 'period',
  },
  //Tổng tiền VND - bao gồm VAT
  totalAmountVat: {
    formula: 'data.totalAmountForeignVat * data.rateInPeriod',
    groupFormula: 'period',
  },
  //Tổng tiền VND - chưa bao gồm VAT
  totalAmount: {
    formula: 'data.totalAmountForeign * data.rateInPeriod',
    groupFormula: 'period',
  },
  //Tổng số phòng đơn
  totalSingleRoom: {
    formula: 'data.singleRoom + data.singleRoomReserved + data.singleRoomOther',
  },
  //Tổng số phòng đôi
  totalDoubleRoom: {
    formula: 'data.doubleRoom + data.doubleRoomOther',
  },

}

export const rawData = {
  id: 1,
  planBudgetProcSummaryId: 101,
  type: 'Hotel',
  periodStart: new Date(2024, 11, 1),
  aircraftType: 'Boeing 737',

  periodEnd: '2024-12-31',
  overnight: 5,
  singleRoom: 10,
  doubleRoom: 5,
  singleRoomReserved: 2,
  singleRoomOther: 1,
  doubleRoomOther: 1,
  singleRoomEarly: 1,
  doubleRoomEarly: 1,
  singleRoomEarlyReserved: 1,
  singleRoomLate: 1,
  doubleRoomLate: 1,
  singleRoomLateReserved: 1,
  totalAmountForeignTransport: 1000,
  totalAmountForeign: 5000, //Tổng tiền ngoại tệ - Chưa bao gồm VAT
  totalAmountForeignVat: 5000, // Tổng tiền ngoại tệ - Bao gồm VAT
  totalAmount: 6000,
  totalAmountVat: 6600,
  priceSingleRoom: 100,
  priceDoubleRoom: 200,
  priceSingleRoomEarly: 150,
  priceDoubleRoomEarly: 250,
  priceSingleRoomLate: 120,
  priceDoubleRoomLate: 220,
  priceCrewTransport: 75000,


  totalFlightMonth: 100, // tổng số chuyến bay trong tháng
  carRate: 75000, // Đơn giá xe chở tổ bay/lượt
  totalAmountForeignSingleRoom: 100, // Thành tiền ngoại tệ, - phòng đơn
  totalAmountForeignDoubleRoom: 50, // Thành tiền ngoại tệ, - phòng đôi
  totalAmountForeignEarly: 50, // Thành tiền ngoại tệ,  - phòng early-checkin
  totalAmountForeignLate: 50, // Thành tiền ngoại tệ,  - phòng late-checkout
  totalAmountAircraft: 1000, // Tổng tiền theo loại máy bay
  rateForeign: 1.1, // Tỷ giá ngoại tệ
  totalFlightByAircraft: 50, // Số chuyến bay theo tàu
  numberOfPilots: 4, //Số phi công
  attendantNumber: 5, //Số tiếp viên	
  rateForSingle: 1.1, // TỈ lệ dự phòng lẻ nam/nữ (dành cho khách sạn)
  numberOfEarlyFlights: 10, // Số chuyến bay early-checkin
  numberOfLateFlights: 5, // Số chuyến bay late-checkout
  overnightLate: 1, // Số đêm late-checkout


};

export const contractData = {
  // Phí early-checkin
  earlyCheckinFeeFlag: true,
  //Phí late checkout
  lateCheckoutFeeFlag: true,
  //Phí thuê xe chở tổ bay
  crewTransportFeeFlag: true,
  //Phí thuê xe chở tổ bay
  priceCrewTransportFlag: true,
}

export function getHeaderRowDef1(contractData: any, type: string): string[] {
  const columns: { column: string, visible: boolean }[] = [
    { column: "month", visible: true },
    { column: "aircraftType", visible: true },
    { column: "overnight", visible: true },
    { column: "numberOfRooms", visible: true },
    { column: "numberOfRoomsForOthers", visible: true },
    { column: "numberOfEstimatedEarlyCheckInRooms", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "numberOfEstimatedLateCheckoutRooms", visible: !!contractData.lateCheckoutFeeFlag },
    //start phần kế hoạch mua sắm
    { column: "unitPriceIncludingVat", visible: type === 'PROCUREMENT' }, // (Đơn giá bao gồm vat) 
    { column: "priceCrewTransport", visible: type === 'PROCUREMENT' && !!contractData.priceCrewTransportFlag }, // (Đơn giá xe chở tổ bay/lượt) 
    // end phần kế hoạch mua sắm
    { column: "totalAmountForeignTransport", visible: !!contractData.crewTransportFeeFlag },
    { column: "totalAmountForeignColspan", visible: true },
    { column: "totalAmountColspan", visible: true }
  ]
  return columns.filter((column: any) => column.visible).map((column: any) => column.column)
}

export function getHeaderRowDef2(contractData: any, type: string): string[] {
  const columns: { column: string, visible: boolean }[] = [
    { column: "singleRoom", visible: true },
    { column: "doubleRoom", visible: true },
    { column: "singleRoomReserved", visible: true },
    { column: "singleRoomOther", visible: true },
    { column: "doubleRoomOther", visible: true },
    { column: "singleRoomEarly", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "doubleRoomEarly", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "singleRoomEarlyReserved", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "singleRoomLate", visible: !!contractData.lateCheckoutFeeFlag },
    { column: "doubleRoomLate", visible: !!contractData.lateCheckoutFeeFlag },
    { column: "singleRoomLateReserved", visible: !!contractData.lateCheckoutFeeFlag },
    //start phần kế hoạch mua sắm
    { column: "priceSingleRoom", visible: type === 'PROCUREMENT' }, // (Đơn giá phòng đơn) 
    { column: "priceDoubleRoom", visible: type === 'PROCUREMENT' }, // (Đơn giá phòng đôi) 
    { column: "priceSingleRoomEarly", visible: type === 'PROCUREMENT' && !!contractData.earlyCheckinFeeFlag }, // (Đơn giá Early-checkin phòng đơn) 
    { column: "priceDoubleRoomEarly", visible: type === 'PROCUREMENT' && !!contractData.earlyCheckinFeeFlag }, // (Đơn giá Early-checkin phòng đôi) 
    { column: "priceSingleRoomLate", visible: type === 'PROCUREMENT' && !!contractData.lateCheckoutFeeFlag }, // (Đơn giá late checkout phòng đơn) 
    { column: "priceDoubleRoomLate", visible: type === 'PROCUREMENT' && !!contractData.lateCheckoutFeeFlag }, // (Đơn giá late check out phòng đôi) 
    // end phần kế hoạch mua sắm
    { column: "totalAmountForeign", visible: true },
    { column: "totalAmountForeignVat", visible: true },
    { column: "totalAmount", visible: true },
    { column: "totalAmountVat", visible: true },
  ];
  return columns.filter((column: any) => column.visible).map((column: any) => column.column)
}

export function getRowDef(contractData: any, type: string): string[] {
  const columns = [
    { column: "month", visible: true },
    { column: "aircraftType", visible: true },
    { column: "overnight", visible: true },
    { column: "singleRoom", visible: true },
    { column: "doubleRoom", visible: true },
    { column: "singleRoomReserved", visible: true },
    { column: "singleRoomOther", visible: true },
    { column: "doubleRoomOther", visible: true },
    { column: "singleRoomEarly", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "doubleRoomEarly", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "singleRoomEarlyReserved", visible: !!contractData.earlyCheckinFeeFlag },
    { column: "singleRoomLate", visible: !!contractData.lateCheckoutFeeFlag },
    { column: "doubleRoomLate", visible: !!contractData.lateCheckoutFeeFlag },
    { column: "singleRoomLateReserved", visible: !!contractData.lateCheckoutFeeFlag },
    //start phần kế hoạch mua sắm
    { column: "priceSingleRoom", visible: type === 'PROCUREMENT' },
    { column: "priceDoubleRoom", visible: type === 'PROCUREMENT' },
    { column: "priceSingleRoomEarly", visible: type === 'PROCUREMENT' && !!contractData.earlyCheckinFeeFlag },
    { column: "priceDoubleRoomEarly", visible: type === 'PROCUREMENT' && !!contractData.earlyCheckinFeeFlag },
    { column: "priceSingleRoomLate", visible: type === 'PROCUREMENT' && !!contractData.lateCheckoutFeeFlag },
    { column: "priceDoubleRoomLate", visible: type === 'PROCUREMENT' && !!contractData.lateCheckoutFeeFlag },
    { column: "priceCrewTransport", visible: type === 'PROCUREMENT' && !!contractData.priceCrewTransportFlag },
    // end phần kế hoạch mua sắm
    { column: "totalAmountForeignTransport", visible: !!contractData.crewTransportFeeFlag },
    { column: "totalAmountForeign", visible: true },
    { column: "totalAmountForeignVat", visible: true },
    { column: "totalAmount", visible: true },
    { column: "totalAmountVat", visible: true },
  ];
  return columns.filter((column: any) => column.visible).map((column: any) => column.column)
}

export const exampleData =
  [
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-11-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 0,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-11-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 0,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-11-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-11-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    }
    ,
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-12-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-12-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-12-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2024-12-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-01-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-01-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-01-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-01-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-02-28T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-02-28T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-02-28T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-02-28T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-03-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-03-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-03-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-03-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-04-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-04-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-04-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-04-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-05-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-05-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-05-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-05-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-06-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-06-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-06-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-06-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-07-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-07-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-07-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-07-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-08-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-08-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-08-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-08-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-09-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-09-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-09-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-09-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-10-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-10-31T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-10-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-10-31T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-11-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-11-30T17:00:00.000Z",
      "aircraftType": "B787",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-11-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 1,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    },
    {
      "id": 1,
      "planBudgetProcSummaryId": 101,
      "type": "Hotel",
      "periodStart": "2025-11-30T17:00:00.000Z",
      "aircraftType": "A321",
      "periodEnd": "2024-12-31",
      "overnight": 2,
      "singleRoom": 10,
      "doubleRoom": 5,
      "singleRoomReserved": 2,
      "singleRoomOther": 1,
      "doubleRoomOther": 1,
      "singleRoomEarly": 1,
      "doubleRoomEarly": 1,
      "singleRoomEarlyReserved": 1,
      "singleRoomLate": 1,
      "doubleRoomLate": 1,
      "singleRoomLateReserved": 1,
      "totalAmountForeignTransport": 1000,
      "totalAmountForeign": 5000,
      "totalAmount": 6000,
      "totalAmountVat": 6600,
      "priceSingleRoom": 100,
      "priceDoubleRoom": 200,
      "priceSingleRoomEarly": 150,
      "priceDoubleRoomEarly": 250,
      "priceSingleRoomLate": 120,
      "priceDoubleRoomLate": 220,
      "priceCrewTransport": 75000,
      "totalFlightMonth": 100,
      "carRate": 75000,
      "totalAmountForeignSingleRoom": 100,
      "totalAmountForeignDoubleRoom": 50,
      "totalAmountForeignEarly": 50,
      "totalAmountForeignLate": 50,
      "totalAmountAircraft": 1000,
      "rateForeign": 1.1,
      "vat": 10,
      "totalFlightByAircraft": 50,
      "numberOfPilots": 4,
      "attendantNumber": 5,
      "rateForSingle": 1.1,
      "numberOfEarlyFlights": 10,
      "numberOfLateFlights": 5,
      "overnightLate": 1
    }
  ];


export const planFlightByOvernight = [
  {
    numberOfOvernight: 1,
    flightRate: 20
  },
  {
    numberOfOvernight: 2,
    flightRate: 30
  },
  {
    numberOfOvernight: 3,
    flightRate: 40
  }
]

export function checkChange(value1: any, value2: any) {
  return value1 && value1 !== value2;
}
